### ISSUE TITLE
Directory must already exist for pull to succeed

### ISSUE THREAD

**Issue by ceball** [dailymuse/git-fit#3]
If I ``git fit push data/file``, then ``rm -r data``, ``git fit pull`` will fail with something like ``data/file: open data/file: no such file or directory``.

With ``path`` being something like ``data/file``,

```go
func download(trans transport.Transport, path string, committedHash string, responseChan chan operationResponse) {
    ...
    if err := util.CopyFile(blob.Path(), path); err != nil {
    ...
```

```go
func CopyFile(fromPath string, toPath string) error {
    ...
    out, err := os.Create(toPath)
    ...
```

**Comment by ysimonson** [comment]
I like this, since it's in-line with git's behavior. Will fix soon.

**Comment by ysimonson** [comment]
Added fix for this in `CopyFile`
