### ISSUE TITLE
Provide some kind of status command?

### ISSUE THREAD

**Issue by ceball** [dailymuse/git-fit#4]
If I have 1000s of data files in e.g. a directory ``data/``, there doesn't seem to be an easy way to tell:
  * if any of those files have been modified since last pushed
  * which files have not been pushed (files I have that are not in git-fit.json)
  * which files have not been pulled (files in git-fit.json that I do not have)

I guess I'm imagining some kind of ``git fit status`` command that would tell me about differences from what's in git-fit.json.

```
$ git status
# On branch master nothing to commit, working directory clean
$ mkdir data
$ echo 1 > data/1
$ echo 2 > data/2
$ git status
# On branch master  
# Untracked files: 
#   (use "git add <file>..." to include in what will be committed)
#                                              
#       data/
# 
nothing added to commit but untracked files present (use "git add" to track)
$ git fit push data/* 
data/1: Synced
data/2: Synced
$ git status
# On branch master                                                                                                                            
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory) 
#
#       modified:   .gitignore
#       modified:   git-fit.json
#
no changes added to commit (use "git add" and/or "git commit -a")
$ git commit -m "Added some data." .gitignore git-fit.json
[master 5ff7da5] Added some data.
 2 files changed, 6 insertions(+), 2 deletions(-)
$ git status
# On branch master 
nothing to commit, working directory clean 
$ rm data/1
$ echo more >> data/2
$ git status # how can I find out about deleted or modified files that are in git-fit.json? 
# On branch master 
nothing to commit, working directory clean 
$ echo 3 > data/3 
$ git status # how can I find out what files are not in git-fit.json?
# On branch master
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
# 
#       data/
# 
nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by ysimonson** [comment]
This makes sense, especially since `pull` will never overwrite local changes. I'll look into implementing this.

**Comment by ysimonson** [comment]
Implemented

**Comment by ceball** [comment]
Wow, that was fast, thanks!

I just wanted to add something about the following aspect:

```go
func Status(schema *config.Config, trans transport.Transport, args []string) {
..
			} else if actualHash != expectedHash {
				util.Message("%s: Out of sync; push the file, or delete it and pull\n", path)
```

(Below I'll explain something I'm wondering about, but I'm not going to submit an issue about it as I'm not sure if it's a good idea...)

I wonder if it would be possible to help the user determine the reason a file is out of sync? (Or alternatively, to help the user avoid getting into a situation where he/she does not know the reason a file is out of sync.)

I really like that git fit does not delete my data. However, as a consequence, there may be times when I'll have to decide what to do, and I'll also have to do it (that is, I'll have to delete my files and ``fit pull``, or I'll have to ``fit push`` my files). Let's say I am working away and I modify some 'fit' files. If I ``git fit push`` these changes before I ``git pull``, then I am ok (I may get a conflict in git-fit.json, but that is fine). If I ``git pull`` before I ``git fit push``, however, and ``git fit status`` tells me that a file is out of sync, I won't know if that's because I modified it (unless I remember...) or because its entry changed in git-fit.json when I did the git pull. 

Maybe this situation could be avoided via some git hooks, but one of the other reasons I like git-fit is  that it's simple and doesn't depend on hooks etc. So I wonder if an alternative might be to provide a new command (or an option to ``status``) that someone could use to figure out why a file is out of sync. For instance, if I could do something like ``git fit status --against HEAD~1``, I could determine that an 'out of sync' file is actually a previous known version (already tracked by git fit), and then I'd know I could safely delete the file. I was vaguely thinking this command could be implemented by getting the ``--against`` argument's version of git-fit.json (via e.g. ``git show HEAD~1:git-fit.json``) and (basically) using that in the status function (in place of the local copy of git-fit.json, which would be the default with no ``--against`` argument).

**Comment by ysimonson** [comment]
Interesting. On the one hand, `gc` could also be substantially improved by peering into alternative/previous histories of the repo, but on the other hand I think the complexity - which git-fit is very much designed to avoid - probably outweighs the value. One thing that seems important to me is that users don't have to learn an entirely new bag of tricks to use git-fit - it should "just work", even if it's kinda dumb about the way it works sometimes.

That said, there is still very much the open issue of how a user might resolve how an asset is out of sync. What if `git fit status` showed the expected hash value of the file vs the actual in its output? You could then compare the actual hash against the history of `git-fit.json` to see if it's an old version of the asset.

**Comment by ceball** [comment]
I completely agree with your desire to keep git-fit simple. I'll think about your proposal while I try out some 'real life' workflows, and then get back to you (in an issue, or ideally via a PR!).
