### ISSUE TITLE
By default, make git-fit commands only report things that might need action?

### ISSUE THREAD

**Issue by ceball** [dailymuse/git-fit#5]
I think I don't usually want to hear about files that are already sync'd when I pull (or ask for status, etc). 

If I have thousands of files in git-dat, messages about files already being sync'd (which I don't have to do anything about) may drown out messages about actions I should take.

I guess I'm thinking about git itself here, which e.g. for status only reports files that differ in some way. 

Maybe there could be a verbose option? Or am I missing a good reason for the 'no action needed' messages?

**Comment by ysimonson** [comment]
That makes sense. I've removed the message all-together. It may make sense to re-introduce an overall status message if people assume that no output suggests that nothing happened, but tentatively going to see if this is fine.
