### ISSUE TITLE
Globbing support for push

### ISSUE THREAD

**Issue by jonstuebe** [dailymuse/git-fit#6]
It would be great if you could push files via globbing:

`git fit push assets/images/**/*.jpg`

or

`git fit push *.jpg`

**Comment by ysimonson** [comment]
That makes sense. It's not a use case we particularly need internally, but I'd be happy to take a look at a PR that includes the functionality. Luckily, go has built-in support for globbing too: https://golang.org/pkg/path/filepath/#Glob
